### ISSUE TITLE
Filter does not work on table

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/arranger#305]
Filter on the table returns this: 

<img width="1390" alt="screen shot 2018-03-27 at 3 47 30 pm" src="https://user-images.githubusercontent.com/15824252/37991090-377859c8-31d6-11e8-9d31-faad9e18100e.png">
<img width="728" alt="screen shot 2018-03-27 at 3 47 26 pm" src="https://user-images.githubusercontent.com/15824252/37991091-3783815e-31d6-11e8-8d39-5501e235d829.png">

**Comment by Jephuff** [comment]
This shouldn't be happening anymore on the beta portal. 
The problem was file_size was set to a type of `ID` as a way to hide it from aggregations. We should add a way to hide aggregations without changing the type.

My suggestion was to do something like the table columns having a `show` check for default columns and `active` for all columns, anything without the `active` check wouldn't show up.

@rosibaj Did you make a ticket? If not I can make one now :)

**Comment by phuongmy** [comment]
Created https://github.com/overture-stack/arranger/issues/306

**Comment by phuongmy** [comment]
I'm surprised though, I believe you encountered the bug again yesterday @rosibaj ?
We changed the type of file_size back to number a while ago.

**Comment by rosibaj** [comment]
@phuongmy yes, i encountered it yesterday.  Was it somehow moved back?

**Comment by phuongmy** [comment]
Does it work for you now? With the same fields you were filtering on?

**Comment by rosibaj** [comment]
Yes it works now!

**Comment by Jephuff** [comment]
Oh yeah, it was `type = id` yesterday, but I changed it :)

**Comment by phuongmy** [comment]
ok mystery solved :), thanks! Closing the ticket.
