### ISSUE TITLE
Separate the admin as a new endpoint 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/arranger#448]
- Separate the search and admin apis
-

**Comment by hlminh2000** [comment]
So instead of splitting this out as a new service, which may introduce a lot of other headaches, we are going to consolidate all the admin API into a common endpoint separate from the projects and have a new UI to interface with that endpoint. We will effectively remove the concept of "Arrange" and have all endpoints available at all times, removing any run-time state that's in the arranger server
