### ISSUE TITLE
Add optional auth for elasticsearch clients

### ISSUE THREAD

**Issue by rtisma** [overture-stack/arranger#618]
If the elasticsearch service requires authorization, a username and password will be needed by the ES client. Currently, there is no support for a secured ES cluster.

**Comment by b-f-chan** [comment]
Consensus among team after consultation with @hlminh2000:

- Add ES_USERNAME, ES_PASSWORD as optional & backwards-compatible configs to Arranger
- This will take priority over DMS Installer work so we can unblock DMS-UI dev & testing, and finally resolve the Arranger issues

**Some notes for context:**

- ES has auth and we do not want to disable this as general security best practice
- Just for testing, @rtisma tried to disable ES auth to see if he could get Arranger working, but could not
- In ARGO, Arranger is not aware of ES_USERNAME, ES_PASSWORD, yet still works with ES auth enabled
- This is because for ARGO, Arranger is not deployed standalone but has the benefit of being instantiated as part of the platform gateway, with an ES client provided conveniently as a dependency in memory
- Arranger is standalone in DMS and used differently than in ARGO, hence we need to make this change
- The solution proposed above is the quickest and most practical way to get around this

Adding to Sprint 7.

**Comment by b-f-chan** [comment]
Confirmed with @rtisma Arranger has been updated to handle ES auth settings, has been reviewed and released
