### ISSUE TITLE
Create Theming System

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/arranger#734]
Create theming system from which CSS properties can be read from and applied

There will be a theme file ultimately that can be ingested, but a system needs to be built support this overall.

---
Closes #280

**Comment by caravinci** [comment]
Status update: I've committed and published two rounds of theming.

Changes thus far as par of this ticket:
- Theming system is up and running in the latest Arranger-components beta (and DMS-UI rewrite branch).
- There's a default Arranger theme, with basic styling for some components (Facets-centred for now) and extended color options (mostly unused but available for users to customise with) out of the box. 
- The default theme is loosely based on DMS-UI styling choices (albeit much less colourful) and while enabled by default, It can be disabled with a props flag.
- In order to greatly facilitate migration for existing apps, the `<Arranger />` root component (to be deprecated in favour of the DCP) now also instantiates the theme provider. I will continue working on integrating the DCP itself in here, after theming is done, aiming to allow a straight simple swap-out. TODO.
- Most theming can be aggregated with partials and/or overridden entirely in multiple ways.
- The system allows inputting custom global theme override at the DCP, or at any additional Theme Providers (which are not really necessary, but possible), and directly at the theme context consumer hook for local overrides.

Bonus: The facet panel theming should fully address #779.

**Comment by caravinci** [comment]
Additional changes included in `beta.10`:
- Improves theming for ArrowIcon and ToggleButton components.
- renames `defaultTheme` to `baseTheme` (thanks @joneubank for the suggestion).
- adds theming capabilities to the Boolean, Date, and Range aggregations.
- reorganises the data and theme context files.

**Comment by caravinci** [comment]
Additional changes included in `beta.11`:
- Refactor `SQONViewer` (formerly multiple different components headed by `CurrentSQON`).
- Fix a bug in the range aggregation, that wasn't letting it be reset when you press the "clear" button in the SQON viewer
- Relocate the "extended mapping" fetching into the data context provider. This ensures a single source of truth (and avoids supefluous API requests), both for the SQON/query viewer and the tables' columnState component.
- improve the server start-up logging

As the next theming steps are related to the table components, which requires a full rewrite (due to its outdated `react-table` dependency, I'm doing that work as a separate ticket.

The theming system is in place and functioning, so I'm closing this ticket. Further theming will be done as separate tasks from now on.
