### ISSUE TITLE
Search icon in facet does not open when facet is collapsed 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/arranger#779]
- collapse the facet 
- click the search icon. the cursor indicated i can click search. 
- nothing happens. 

![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/f2f86e22-8176-448c-afbe-5de2fbbafba2)

**Comment by b-f-chan** [comment]
Re-assign to @caravinci in backlog - NOT priority for now

**Comment by caravinci** [comment]
Funny enough, hiding that icon is something I was already thinking of last week while working on the facets' theming.

**Comment by b-f-chan** [comment]
Awesome, that sounds good, thanks @caravinci!

**Comment by kcullion** [comment]
@b-f-chan @caravinci @ciaranschutte 
hiding (not dimming) the search icon when the facet is closed is what we did in argo: https://platform.icgc-argo.org/repository?filters=%7B%22content%22%3A%5B%5D%2C%22op%22%3A%22and%22%7D

I think this is fine because the search is for filtering the value list - when it's close you can't see that list so no need to search it.

**Comment by caravinci** [comment]
Perfect! I'll make sure to do that. Thanks everyone!

**Comment by b-f-chan** [comment]
Thanks @kcullion !  We will follow ARGO standard then.  @caravinci this is not priority, but if you can sneak this into the UI epic that would great :)

**Comment by caravinci** [comment]
Update: the fix for this ticket is already included in the `Arranger@3.0.0-beta.8` version. 
Will move this ticket to `ready for QA` for now. To be closed once we figure DMS-UI integration testing.
Adding `rewrite` ticket label to include it in that context.
